name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
        - main
   # paths:
  #    - 'index.html'  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Set up Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-ci-cd:latest .

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/nginx-ci-cd:latest

    - name: Deploy using Docker Compose
      run: |
        docker-compose down
        docker-compose up -d
