FROM python:3.9.5-slim-buster

WORKDIR /app

COPY requirements.txt .
RUN apt-get update && apt-get install -y libpq-dev python3-dev build-essential netcat
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN chmod +x entrypoint.sh

EXPOSE 8000

ENV PYTHONUNBUFFERED=1

CMD ["./entrypoint.sh"]

#Todos los comandos se ejecutan cuando estas en docker build y el ultimo comando se deberia ejecutar cuando esta en docker run