# Usar una imagen base ligera de Python
FROM node:18-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de requerimientos e instalar dependencias
COPY package*.json .

#Instala dependencias
RUN npm install

# Copiar el código del proyecto
COPY . .

# Asegurarse de que el script de entrada tenga permisos de ejecución
RUN npm install

# Exponer el puerto donde correrá Django
EXPOSE 3000

# Comando por defecto para ejecutar el proyecto
CMD ["npm" , "start"]
