# Usar una imagen base ligera de Node
FROM node:18-alpine

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar el archivo de requerimientos e instalar dependencias
COPY package*.json .

#Instala dependencias
RUN npm install

# Copiar el código del proyecto
COPY . .

# Exponer el puerto donde correrá Node.js
EXPOSE 3000

# Comando por defecto para ejecutar el proyecto
CMD ["npm" , "start"]
